### ISSUE TITLE
FrontEndServiceProvider Not Found

### ISSUE THREAD

**Issue by RKillinger37** [FSVAOS/VAOS#174]
Hi,

So, tried working on it again and now today, I get a 500 error page and this in the laravel.log

`[2019-08-29 18:47:45] local.ERROR: Class 'Modules\FrontEnd\Providers\FrontEndServiceProvider' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Modules\\FrontEnd\\Providers\\FrontEndServiceProvider' not found at /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208)
[stacktrace]
#0 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider('Modules\\\\FrontEn...')
#1 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest(Array)
#2 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/nwidart/laravel-modules/src/Laravel/Module.php(27): Illuminate\\Foundation\\ProviderRepository->load(Array)
#3 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/nwidart/laravel-modules/src/Module.php(251): Nwidart\\Modules\\Laravel\\Module->registerProviders()
#4 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/nwidart/laravel-modules/src/Repository.php(299): Nwidart\\Modules\\Module->register()
#5 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\Repository->register()
#6 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#7 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register(Object(Nwidart\\Modules\\Providers\\BootstrapServiceProvider))
#8 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#9 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#10 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#15 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Nwidart\\Modules\\LaravelModulesServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Nwidart\\Modules\\LaravelModulesServiceProvider), 18)
#17 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#18 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /home/marrymem/kingsleyexecutivejet.tk/pilotcenter/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 /home/marrymem/kingsleyexecutivejet.tk/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 {main}
"} `

Not sure what's going on. I checked the folders and the file is there. Updated the url's in index and boot file.

**Comment by BossOfGames** [comment]
That's a new one. Let me investigate what's going on there. Did you make any significant changes to any of the files to generate this error?

**Comment by RKillinger37** [comment]
Nope, this was a fresh upload. All I did was renamed the vaos folder to pilotcenter and updated the urls in index and boot.
