### ISSUE TITLE
Laravel Artisan Key Generate Prevents Installation

### ISSUE THREAD

**Issue by lucafano04** [FSVAOS/VAOS#209]
[2021-06-15 12:15:13] local.ERROR: Trying to access array offset on value of type int {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type int at ./vendor/symfony/console/Input/ArrayInput.php:135)
[stacktrace]
#0 ./vendor/symfony/console/Input/ArrayInput.php(135): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 ./vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArrayInput->parse()
#2 ./vendor/symfony/console/Application.php(207): Symfony\\Component\\Console\\Input\\Input->bind()
#3 ./vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#4 ./vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#5 ./vendor/laravel/framework/src/Illuminate/Console/Application.php(177): Illuminate\\Console\\Application->run()
#6 ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(249): Illuminate\\Console\\Application->call()
#7 ./vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call()
#8 ./app/Http/Controllers/Admin/InstallController.php(37): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 [internal function]: App\\Http\\Controllers\\Admin\\InstallController->doInstall()
#10 ./vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#11 ./vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#12 ./vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 ./vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#14 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#15 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 ./vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#17 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#18 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#20 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 ./vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#23 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#24 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 ./vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#26 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#27 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 ./vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#29 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 ./vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#32 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#35 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then()
#36 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#38 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#39 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#40 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#43 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#46 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#47 ./public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#48 {main}
"}

This is the laravel.log output I have a 500 error during the ./install page.

**Comment by lucafano04** [comment]
This is the laravel.log output I have a 500 error during the ./install page.

**Comment by BossOfGames** [comment]
What version is this that you're running? Are you running any of the released versions?

**Comment by lucafano04** [comment]
I'm trying to run Last Release

**Comment by BossOfGames** [comment]
Ok, looking into the error, if you're running the regular 2.0 release and not the 2.1 branch (not production ready yet), it's erroring out here:

./app/Http/Controllers/Admin/InstallController.php(37): Illuminate\Support\Facades\Facade::__callStatic()
```php
if (! Schema::hasTable('users')) {
            Artisan::call('key:generate'); // Line 37 where the error sits.
            // Run the database migration
            Artisan::call('migrate');
```
Basically I'm regenerating your encryption key so that way your stuff is secured. In the new version of VAOS, I encapsulated this in a try/catch to let you know this is exactly the reason.

```php
        try {
            Artisan::call('key:generate'); // Errors out here at Line 38
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'error' => "Unable to generate encryption key. Full details: {$e}"
            ]);
        }
```
Judging by that you got this far into the install, I'm going to assume you have a `.env` file created in the appropriate directory to hold your settings?

An alternative to work around this issue would be to comment out that `Artisan::call('key:generate');` line by using `//` at the beginning like so:  `// Artisan::call('key:generate');`, but you'll be running the default password encryption key found in the example files. If you have command line access, you could also theoretically run all the install commands from the command line.

Also, thank you for being an absolute lad by providing the stack trace. You have no idea the amount of back and forth we would have if you didn't do so.

**Comment by lucafano04** [comment]
ok, I tried both solutions, the substitution with try-catch and the comment one, none of that worked can you say the install command for the command line? Thanks.
P.S. The first method sayed this:
`{"success":false,"error":"Unable to generate encryption key. Full details: ErrorException: Trying to access array offset on value of type int in .\/vendor\/symfony\/console\/Input\/ArrayInput.php:135\nStack trace:\n#0 .\/vendor\/symfony\/console\/Input\/ArrayInput.php(135): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 .\/vendor\/symfony\/console\/Input\/Input.php(55): Symfony\\Component\\Console\\Input\\ArrayInput->parse()\n#2 .\/vendor\/symfony\/console\/Application.php(207): Symfony\\Component\\Console\\Input\\Input->bind()\n#3 .\/vendor\/symfony\/console\/Application.php(148): Symfony\\Component\\Console\\Application->doRun()\n#4 .\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php(88): Symfony\\Component\\Console\\Application->run()\n#5 .\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php(177): Illuminate\\Console\\Application->run()\n#6 .\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php(249): Illuminate\\Console\\Application->call()\n#7 .\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call()\n#8 .\/app\/Http\/Controllers\/Admin\/InstallController.php(38): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#9 [internal function]: App\\Http\\Controllers\\Admin\\InstallController->doInstall()\n#10 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(54): call_user_func_array()\n#11 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()\n#12 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()\n#13 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(169): Illuminate\\Routing\\Route->runController()\n#14 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(658): Illuminate\\Routing\\Route->run()\n#15 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()\n#16 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#17 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()\n#18 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#19 .\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#20 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()\n#21 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#22 .\/vendor\/laravel\/framework\/src\/Illuminate\/View\/Middleware\/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#23 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()\n#24 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#25 .\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware\/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#26 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()\n#27 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#28 .\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#29 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()\n#30 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#31 .\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#32 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()\n#33 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#34 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#35 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(660): Illuminate\\Pipeline\\Pipeline->then()\n#36 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()\n#37 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(601): Illuminate\\Routing\\Router->runRoute()\n#38 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()\n#39 .\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()\n#40 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()\n#41 .\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#42 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()\n#43 .\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#44 .\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()\n#45 .\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()\n#46 .\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()\n#47 .\/public\/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()\n#48 {main}"}`
The second method says 500 and on laravel.log:
`[2021-06-18 08:05:06] local.ERROR: Trying to access array offset on value of type int {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type int at ./vendor/symfony/console/Input/ArrayInput.php:135)
[stacktrace]
#0 ./vendor/symfony/console/Input/ArrayInput.php(135): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 ./vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArrayInput->parse()
#2 ./vendor/symfony/console/Application.php(207): Symfony\\Component\\Console\\Input\\Input->bind()
#3 ./vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#4 ./vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#5 ./vendor/laravel/framework/src/Illuminate/Console/Application.php(177): Illuminate\\Console\\Application->run()
#6 ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(249): Illuminate\\Console\\Application->call()
#7 ./vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call()
#8 ./app/Http/Controllers/Admin/InstallController.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 [internal function]: App\\Http\\Controllers\\Admin\\InstallController->doInstall()
#10 ./vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#11 ./vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#12 ./vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 ./vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#14 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#15 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 ./vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#17 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#18 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#20 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 ./vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#23 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#24 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 ./vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#26 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#27 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 ./vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#29 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 ./vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#32 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#35 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then()
#36 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#38 ./vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#39 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#40 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#43 ./vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#46 ./vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#47 ./public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#48 {main}
`

P.P.S. I substituted the full directory with a . to simplify the job for you and due to privacy.

**Comment by BossOfGames** [comment]
So from the command line, just do `php artisan migrate` then manually create an account and give yourself admin by modifying the users table and setting `admin` from 0 to 1. That'll basically install the system for you manually.
